"""
Packet Capture & Port Monitoring Engine
========================================
Deep traffic analysis layer for the MITM detection system.

Capabilities:
  - Real-time traffic statistics (PPS, in/out ratio, protocol breakdown)
  - Port scan detection (per-IP unique port tracking)
  - Port flood detection (high packet rate to ports)
  - DDoS indicator detection (sustained high PPS)
  - Sensitive port access monitoring (SSH, RDP, SMB, FTP)
  - Suspicious external IP flagging
  - Top talker identification

Architecture:
  Integrates as an additional detection layer in the MitmDetector pipeline.
  Generates PacketCaptureEvent objects that feed into the RiskScoringEngine.

  ┌──────────────┐     ┌─────────────────────┐     ┌──────────────┐
  │ Scapy Packet │ ──→ │ PacketCaptureEngine │ ──→ │ RiskScoring  │
  │ (hot path)   │     │  • port tracking     │     │ Engine       │
  └──────────────┘     │  • rate analysis     │     └──────────────┘
                       │  • protocol stats    │
                       └─────────────────────┘

Thread Safety:
  All mutable state is protected by a single lock. The hot path
  (record_packet) does minimal work under the lock; the heavy
  analysis runs periodically in the background analysis thread.
"""

import time
import socket
import logging
import threading
from collections import defaultdict, deque
from dataclasses import dataclass, field
from typing import Dict, List, Set, Optional, Deque, Tuple

logger = logging.getLogger("mitm.packet_capture")


# ─────────────────────────────────────────────
# Configuration (injected from config.py)
# ─────────────────────────────────────────────

@dataclass
class PacketCaptureConfig:
    """Tunable thresholds for packet capture analysis."""

    # ── Analysis Window ──
    analysis_window_seconds: float = 5.0       # Window for rate calculations

    # ── DDoS Detection ──
    ddos_pps_threshold: float = 100.0          # Packets/sec to trigger DDoS alert
    ddos_sustained_windows: int = 2            # Consecutive windows above threshold

    # ── Port Scan Detection ──
    port_scan_threshold: int = 10              # Unique ports from one IP = scan
    port_scan_window_seconds: float = 10.0     # Window for port scan tracking

    # ── Port Flood Detection ──
    port_flood_threshold: int = 30             # Packets to ports from one IP
    port_flood_window_seconds: float = 5.0     # Window for port flood tracking

    # ── Suspicious External IP ──
    external_ip_packet_threshold: int = 200    # External IP packet count to flag (Increased to reduce FPs)
    private_prefixes: Tuple[str, ...] = (      # Prefixes considered "internal"
        "10.", "172.16.", "172.17.", "172.18.", "172.19.",
        "172.20.", "172.21.", "172.22.", "172.23.", "172.24.",
        "172.25.", "172.26.", "172.27.", "172.28.", "172.29.",
        "172.30.", "172.31.", "192.168.", "127.",
    )

    # ── Sensitive Ports ──
    sensitive_ports: Set[int] = field(default_factory=lambda: {
        21,    # FTP
        22,    # SSH
        23,    # Telnet
        445,   # SMB
        3389,  # RDP
        3306,  # MySQL
        5432,  # PostgreSQL
        1433,  # MSSQL
        6379,  # Redis
        27017, # MongoDB
    })

    # ── Reporting ──
    top_talkers_count: int = 5
    report_interval_seconds: float = 5.0       # Console report interval
    enable_console_report: bool = True         # Print traffic reports

    # ── Capacity ──
    max_tracked_ips: int = 2000
    ip_expiry_seconds: float = 600.0           # Expire IPs not seen for 10 min


# ─────────────────────────────────────────────
# Events
# ─────────────────────────────────────────────

@dataclass
class PacketCaptureEvent:
    """
    Event generated by the packet capture engine.

    Event types:
      - port_scan:         IP accessing many unique ports
      - port_flood:        High packet rate to ports from one IP
      - ddos_indicator:    Sustained high overall packet rate
      - sensitive_port:    Access to known sensitive/admin ports
      - suspicious_external: External IP with high traffic volume
    """
    event_type: str
    source_ip: str
    details: str
    confidence: float = 0.5
    ports: List[int] = field(default_factory=list)
    packet_count: int = 0
    timestamp: float = field(default_factory=time.time)


# ─────────────────────────────────────────────
# Traffic Snapshot (for external consumption)
# ─────────────────────────────────────────────

@dataclass
class TrafficSnapshot:
    """Point-in-time traffic statistics snapshot."""
    window_seconds: float = 0.0
    total_packets: int = 0
    incoming_packets: int = 0
    outgoing_packets: int = 0
    other_packets: int = 0
    tcp_packets: int = 0
    udp_packets: int = 0
    other_proto_packets: int = 0
    packets_per_second: float = 0.0
    top_talkers: List[Tuple[str, int]] = field(default_factory=list)
    top_incoming: List[Tuple[str, int]] = field(default_factory=list)
    port_scan_ips: Dict[str, List[int]] = field(default_factory=dict)
    sensitive_port_hits: Dict[str, List[int]] = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)


# ─────────────────────────────────────────────
# Packet Capture Engine
# ─────────────────────────────────────────────

class PacketCaptureEngine:
    """
    Production packet capture and port monitoring engine.

    Designed to run in the MitmDetector's packet processing pipeline.
    The record_packet() method is called on the hot path — it must be
    fast. Heavy analysis is done periodically via analyze().

    Usage:
        engine = PacketCaptureEngine(config, own_ip="192.168.1.100")

        # Hot path — called per packet
        engine.record_packet(src_ip, dst_ip, protocol, src_port, dst_port)

        # Periodic analysis (called from background thread)
        events = engine.analyze()
        for event in events:
            risk_engine.add_score(event.source_ip, event.event_type, ...)
    """

    def __init__(
        self,
        config: PacketCaptureConfig = None,
        own_ip: str = "127.0.0.1",
    ):
        self._cfg = config or PacketCaptureConfig()
        self._own_ip = own_ip
        self._lock = threading.Lock()

        # ── Counters (reset each analysis window) ──
        self._packet_count = 0
        self._incoming_count = 0
        self._outgoing_count = 0
        self._tcp_count = 0
        self._udp_count = 0
        self._other_proto_count = 0

        # ── Per-IP Tracking ──
        self._ip_count: Dict[str, int] = defaultdict(int)
        self._incoming_ip_count: Dict[str, int] = defaultdict(int)

        # ── Port Tracking ──
        # IP → set of unique destination ports accessed
        self._port_scan: Dict[str, Set[int]] = defaultdict(set)
        # IP → total packets to ports
        self._port_count: Dict[str, int] = defaultdict(int)
        # IP → {port → timestamp deque} for time-windowed tracking
        self._port_timestamps: Dict[str, Deque[float]] = defaultdict(
            lambda: deque(maxlen=500)
        )

        # ── DDoS Tracking ──
        self._ddos_consecutive_windows = 0
        self._pps_history: Deque[float] = deque(maxlen=60)

        # ── Window Timer ──
        self._window_start = time.time()

        # ── Event Queue ──
        self._event_queue: Deque[PacketCaptureEvent] = deque(maxlen=500)

        # ── Lifetime Stats ──
        self._lifetime_packets = 0
        self._lifetime_events = 0
        self._lifetime_alerts = {
            "port_scan": 0,
            "port_flood": 0,
            "ddos_indicator": 0,
            "sensitive_port": 0,
            "suspicious_external": 0,
        }

        # ── Last Report Time ──
        self._last_report_time = time.time()

        logger.info(
            "PacketCaptureEngine initialized (own_ip=%s, "
            "ddos_threshold=%.0f pps, port_scan_threshold=%d ports, "
            "sensitive_ports=%s)",
            self._own_ip,
            self._cfg.ddos_pps_threshold,
            self._cfg.port_scan_threshold,
            self._cfg.sensitive_ports,
        )

    # ─────────────────────────────────────────────
    # Hot Path — Called Per Packet
    # ─────────────────────────────────────────────

    def record_packet(
        self,
        src_ip: str,
        dst_ip: str,
        protocol: str,
        src_port: int = 0,
        dst_port: int = 0,
    ):
        """
        Record a packet for traffic analysis.

        This runs on the hot path — must be fast.
        Only increments counters and appends to sets under the lock.

        Args:
            src_ip:   Source IP address
            dst_ip:   Destination IP address
            protocol: "TCP", "UDP", or "OTHER"
            src_port: Source port (0 if not applicable)
            dst_port: Destination port (0 if not applicable)
        """
        now = time.time()

        with self._lock:
            self._packet_count += 1
            self._lifetime_packets += 1
            self._ip_count[src_ip] += 1

            # Protocol counters
            if protocol == "TCP":
                self._tcp_count += 1
            elif protocol == "UDP":
                self._udp_count += 1
            else:
                self._other_proto_count += 1

            # Direction classification
            if dst_ip == self._own_ip:
                # ── Incoming Traffic ──
                self._incoming_count += 1
                self._incoming_ip_count[src_ip] += 1

                # Port tracking (only for incoming traffic)
                if dst_port > 0:
                    self._port_scan[src_ip].add(dst_port)
                    self._port_count[src_ip] += 1
                    self._port_timestamps[src_ip].append(now)

            elif src_ip == self._own_ip:
                # ── Outgoing Traffic ──
                self._outgoing_count += 1

    # ─────────────────────────────────────────────
    # Periodic Analysis — Called from Background Thread
    # ─────────────────────────────────────────────

    def analyze(self) -> List[PacketCaptureEvent]:
        """
        Perform periodic traffic analysis and generate events.

        This method:
          1. Snapshots and resets all window counters
          2. Runs detection algorithms on the snapshot
          3. Optionally prints a console traffic report
          4. Returns a list of detection events

        Should be called every analysis_window_seconds from the
        MitmDetector's analysis loop.
        """
        events: List[PacketCaptureEvent] = []
        now = time.time()

        with self._lock:
            duration = now - self._window_start

            # ── Snapshot current window ──
            snapshot = TrafficSnapshot(
                window_seconds=duration,
                total_packets=self._packet_count,
                incoming_packets=self._incoming_count,
                outgoing_packets=self._outgoing_count,
                other_packets=self._packet_count - self._incoming_count - self._outgoing_count,
                tcp_packets=self._tcp_count,
                udp_packets=self._udp_count,
                other_proto_packets=self._other_proto_count,
                packets_per_second=self._packet_count / duration if duration > 0 else 0,
                timestamp=now,
            )

            # Top talkers
            sorted_ips = sorted(
                self._ip_count.items(), key=lambda x: x[1], reverse=True
            )
            snapshot.top_talkers = sorted_ips[: self._cfg.top_talkers_count]

            # Top incoming sources
            sorted_incoming = sorted(
                self._incoming_ip_count.items(), key=lambda x: x[1], reverse=True
            )
            snapshot.top_incoming = sorted_incoming

            # Copy port data for analysis
            port_scan_copy = {
                ip: sorted(list(ports))
                for ip, ports in self._port_scan.items()
            }
            port_count_copy = dict(self._port_count)
            incoming_ips_copy = dict(self._incoming_ip_count)

            # ── Reset window counters ──
            self._packet_count = 0
            self._incoming_count = 0
            self._outgoing_count = 0
            self._tcp_count = 0
            self._udp_count = 0
            self._other_proto_count = 0
            self._ip_count.clear()
            self._incoming_ip_count.clear()
            self._port_scan.clear()
            self._port_count.clear()
            self._port_timestamps.clear()
            self._window_start = now

        # ── Run Detection Algorithms (outside lock) ──
        pps = snapshot.packets_per_second

        # 1. DDoS Detection
        self._pps_history.append(pps)
        ddos_events = self._detect_ddos(pps)
        events.extend(ddos_events)

        # 2. Port Scan Detection
        scan_events = self._detect_port_scan(port_scan_copy)
        events.extend(scan_events)

        # 3. Port Flood Detection
        flood_events = self._detect_port_flood(port_count_copy)
        events.extend(flood_events)

        # 4. Sensitive Port Access
        sensitive_events = self._detect_sensitive_ports(port_scan_copy)
        events.extend(sensitive_events)
        snapshot.sensitive_port_hits = {
            ip: ports for ip, ports in port_scan_copy.items()
            if self._cfg.sensitive_ports.intersection(ports)
        }

        # 5. Suspicious External IP
        external_events = self._detect_suspicious_external(incoming_ips_copy)
        events.extend(external_events)

        # Store port scan data in snapshot
        snapshot.port_scan_ips = {
            ip: ports for ip, ports in port_scan_copy.items()
            if len(ports) >= 3  # Only show IPs with 3+ ports
        }

        # ── Queue Events ──
        for event in events:
            self._event_queue.append(event)
            self._lifetime_events += 1
            if event.event_type in self._lifetime_alerts:
                self._lifetime_alerts[event.event_type] += 1

        # ── Console Report ──
        if self._cfg.enable_console_report:
            if (now - self._last_report_time) >= self._cfg.report_interval_seconds:
                self._print_traffic_report(snapshot, port_scan_copy, events)
                self._last_report_time = now

        return events

    # ─────────────────────────────────────────────
    # Detection Algorithms
    # ─────────────────────────────────────────────

    def _detect_ddos(self, pps: float) -> List[PacketCaptureEvent]:
        """Detect sustained high packet rates indicating DDoS."""
        events = []

        if pps > self._cfg.ddos_pps_threshold:
            self._ddos_consecutive_windows += 1

            if self._ddos_consecutive_windows >= self._cfg.ddos_sustained_windows:
                avg_pps = sum(self._pps_history) / len(self._pps_history) if self._pps_history else pps
                event = PacketCaptureEvent(
                    event_type="ddos_indicator",
                    source_ip="0.0.0.0",  # Network-wide event
                    details=(
                        f"Sustained high traffic: {pps:.1f} pps "
                        f"(threshold: {self._cfg.ddos_pps_threshold:.0f}, "
                        f"sustained: {self._ddos_consecutive_windows} windows, "
                        f"avg: {avg_pps:.1f} pps)"
                    ),
                    confidence=min(0.5 + (self._ddos_consecutive_windows * 0.1), 0.95),
                    packet_count=int(pps * self._cfg.analysis_window_seconds),
                )
                events.append(event)
                logger.warning(
                    "DDoS indicator: %.1f pps sustained for %d windows",
                    pps, self._ddos_consecutive_windows,
                )
        else:
            self._ddos_consecutive_windows = 0

        return events

    def _detect_port_scan(
        self, port_scan_data: Dict[str, List[int]]
    ) -> List[PacketCaptureEvent]:
        """Detect IPs accessing many unique ports (port scanning)."""
        events = []

        for ip, ports in port_scan_data.items():
            if len(ports) >= self._cfg.port_scan_threshold:
                event = PacketCaptureEvent(
                    event_type="port_scan",
                    source_ip=ip,
                    details=(
                        f"Port scan detected: {len(ports)} unique ports "
                        f"accessed in {self._cfg.analysis_window_seconds}s window "
                        f"(threshold: {self._cfg.port_scan_threshold}). "
                        f"Ports: {ports[:20]}{'...' if len(ports) > 20 else ''}"
                    ),
                    confidence=min(0.6 + (len(ports) / 50.0), 0.95),
                    ports=ports,
                    packet_count=len(ports),
                )
                events.append(event)
                logger.warning(
                    "Port scan from %s: %d unique ports", ip, len(ports)
                )

        return events

    def _detect_port_flood(
        self, port_count_data: Dict[str, int]
    ) -> List[PacketCaptureEvent]:
        """Detect high-volume traffic to ports from a single IP."""
        events = []

        for ip, count in port_count_data.items():
            if count >= self._cfg.port_flood_threshold:
                event = PacketCaptureEvent(
                    event_type="port_flood",
                    source_ip=ip,
                    details=(
                        f"Port flood detected: {count} packets to ports "
                        f"in {self._cfg.analysis_window_seconds}s window "
                        f"(threshold: {self._cfg.port_flood_threshold})"
                    ),
                    confidence=min(0.5 + (count / 100.0), 0.95),
                    packet_count=count,
                )
                events.append(event)
                logger.warning(
                    "Port flood from %s: %d packets", ip, count
                )

        return events

    def _detect_sensitive_ports(
        self, port_scan_data: Dict[str, List[int]]
    ) -> List[PacketCaptureEvent]:
        """Detect access to known sensitive/administrative ports."""
        events = []

        for ip, ports in port_scan_data.items():
            flagged = self._cfg.sensitive_ports.intersection(ports)
            if flagged:
                port_names = self._get_port_names(flagged)
                event = PacketCaptureEvent(
                    event_type="sensitive_port",
                    source_ip=ip,
                    details=(
                        f"Sensitive port access: {ip} → "
                        f"{', '.join(port_names)} "
                        f"(ports: {sorted(flagged)})"
                    ),
                    confidence=0.6,
                    ports=sorted(flagged),
                )
                events.append(event)
                logger.warning(
                    "Sensitive port access from %s: %s",
                    ip, port_names,
                )

        return events

    def _detect_suspicious_external(
        self, incoming_ips: Dict[str, int]
    ) -> List[PacketCaptureEvent]:
        """Flag external IPs with unusually high traffic volume."""
        events = []

        for ip, count in incoming_ips.items():
            # Skip private/internal IPs
            if self._is_private_ip(ip):
                continue

            # 🛡️ Whitelist: Ignore known benign infrastructure
            # Google (142.250., 172.217., 216.58.), Cloudflare (104.16-31.), DNS (8.8.8.8, 1.1.1.1)
            whitelist = ["8.8.8.8", "1.1.1.1", "142.250.", "172.217.", "216.58.", "104.16.", "104.17.", "104.18."]
            if any(ip.startswith(prefix) for prefix in whitelist):
                continue

            if count >= self._cfg.external_ip_packet_threshold:
                event = PacketCaptureEvent(
                    event_type="suspicious_external",
                    source_ip=ip,
                    details=(
                        f"Suspicious external IP: {ip} sent {count} packets "
                        f"in {self._cfg.analysis_window_seconds}s "
                        f"(threshold: {self._cfg.external_ip_packet_threshold})"
                    ),
                    confidence=min(0.4 + (count / 100.0), 0.85),
                    packet_count=count,
                )
                events.append(event)
                logger.warning(
                    "Suspicious external IP %s: %d packets", ip, count
                )

        return events

    # ─────────────────────────────────────────────
    # Helper Methods
    # ─────────────────────────────────────────────

    def _is_private_ip(self, ip: str) -> bool:
        """Check if an IP belongs to a private/internal range."""
        return any(ip.startswith(prefix) for prefix in self._cfg.private_prefixes)

    @staticmethod
    def _get_port_names(ports: Set[int]) -> List[str]:
        """Map port numbers to human-readable service names."""
        port_map = {
            21: "FTP(21)",
            22: "SSH(22)",
            23: "Telnet(23)",
            445: "SMB(445)",
            3389: "RDP(3389)",
            3306: "MySQL(3306)",
            5432: "PostgreSQL(5432)",
            1433: "MSSQL(1433)",
            6379: "Redis(6379)",
            27017: "MongoDB(27017)",
        }
        return [port_map.get(p, f"Port({p})") for p in sorted(ports)]

    # ─────────────────────────────────────────────
    # Console Traffic Report
    # ─────────────────────────────────────────────

    def _print_traffic_report(
        self,
        snapshot: TrafficSnapshot,
        port_scan_data: Dict[str, List[int]],
        events: List[PacketCaptureEvent],
    ):
        """Print a formatted traffic report to console."""
        print()
        print("┌──────────────────────────────────────────────────────────────┐")
        print("│           📊 TRAFFIC REPORT (Packet Capture Engine)         │")
        print("├──────────────────────────────────────────────────────────────┤")
        print(f"│  Window:       {snapshot.window_seconds:.1f}s                                       │")
        print(f"│  Packets/sec:  {snapshot.packets_per_second:<10.2f}                               │")
        print(f"│  Incoming:     {snapshot.incoming_packets:<10}                               │")
        print(f"│  Outgoing:     {snapshot.outgoing_packets:<10}                               │")
        print(f"│  TCP: {snapshot.tcp_packets:<6}  UDP: {snapshot.udp_packets:<6}  Other: {snapshot.other_proto_packets:<6}        │")
        print("├──────────────────────────────────────────────────────────────┤")

        # Top Talkers
        if snapshot.top_talkers:
            print("│  🔝 Top Talkers:                                           │")
            for ip, count in snapshot.top_talkers:
                print(f"│    {ip:<20} → {count:>6} packets                    │")

        # Incoming Sources
        if snapshot.top_incoming:
            print("│  🎯 Top Incoming Sources:                                  │")
            for ip, count in snapshot.top_incoming[:5]:
                print(f"│    {ip:<20} → {count:>6} packets                    │")

        # Port Access Map
        if port_scan_data:
            active_ports = {ip: ports for ip, ports in port_scan_data.items() if len(ports) >= 2}
            if active_ports:
                print("│  🔌 Port Activity:                                        │")
                for ip, ports in list(active_ports.items())[:5]:
                    port_str = str(ports[:8])
                    if len(ports) > 8:
                        port_str = port_str[:-1] + ", ...]"
                    print(f"│    {ip:<18} → {port_str:<36}│")

        # Alerts from this window
        if events:
            print("├──────────────────────────────────────────────────────────────┤")
            print("│  🚨 ALERTS:                                                │")
            for event in events:
                alert_line = f"    {event.event_type}: {event.source_ip}"
                print(f"│  {alert_line:<58}│")

        print("└──────────────────────────────────────────────────────────────┘")

    # ─────────────────────────────────────────────
    # Public API (for MitmDetector integration)
    # ─────────────────────────────────────────────

    def drain_events(self) -> List[PacketCaptureEvent]:
        """Drain and return all queued events."""
        with self._lock:
            events = list(self._event_queue)
            self._event_queue.clear()
            return events

    def get_stats(self) -> Dict:
        """Get current engine statistics."""
        with self._lock:
            return {
                "lifetime_packets": self._lifetime_packets,
                "lifetime_events": self._lifetime_events,
                "lifetime_alerts": dict(self._lifetime_alerts),
                "pps_history": list(self._pps_history),
                "ddos_consecutive_windows": self._ddos_consecutive_windows,
            }

    def get_latest_snapshot(self) -> Optional[TrafficSnapshot]:
        """Get the latest traffic snapshot without resetting counters."""
        with self._lock:
            now = time.time()
            duration = now - self._window_start
            if duration <= 0:
                return None

            return TrafficSnapshot(
                window_seconds=duration,
                total_packets=self._packet_count,
                incoming_packets=self._incoming_count,
                outgoing_packets=self._outgoing_count,
                tcp_packets=self._tcp_count,
                udp_packets=self._udp_count,
                packets_per_second=self._packet_count / duration,
                timestamp=now,
            )

    def update_own_ip(self, ip: str):
        """Update the own IP (if it changes, e.g., DHCP renewal)."""
        with self._lock:
            old = self._own_ip
            self._own_ip = ip
            if old != ip:
                logger.info("Own IP updated: %s → %s", old, ip)
