services:
  - type: web
    name: hybrid-ai-ids-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend server:app -b 0.0.0.0:$PORT
    envVars:
      - key: MONGO_URI
        sync: false
